### ISSUE TITLE
To deploy

### ISSUE THREAD

**Issue by Mar12358** [Mar12358/to-do-list#6]
- [x] Setup, as always, gh-pages settings from GitHub repository website
- [x] Be sure to merge/pull all changes to main branch
- [x] Be sure to add all src files and dist output to webpack.config.js:
in my case, for example:
![image](https://user-images.githubusercontent.com/120040536/236521028-1ee23107-c966-4c28-afb4-21aa85ba3e3f.png)
![image](https://user-images.githubusercontent.com/120040536/236697188-fd7e58ef-a6ec-4cbe-be1c-f53fdd0a98e6.png)

- [x] checkout to main branch
- [x] Delete existing gh-pages branch (if any)
run:
`git branch -D gh-pages`
`git push --delete origin gh-pages`

- [x] build all dist folders, 
run:
`npm run build`

- [x] Commit dist subtree and push it to new branch, 
run:
`git add dist -f  `
`git commit -m "dist Subtree deployment using webpack"`
`git subtree push --prefix dist origin gh-pages`

**Comment by yegonkimutai** [comment]
Thank you.... Very helpful 😄
